import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import photosRouter from "./photos";
import collectionsRouter from "./collections";
import tagsRouter from "./tags";
import statsRouter from "./stats";
import commentsRouter from "./comments";
import notificationsRouter from "./notifications";
import messagesRouter from "./messages";
import followsRouter from "./follows";
import uploadRouter from "./upload";
import reactionsRouter from "./reactions";
import reportsRouter from "./reports";
import seriesRouter from "./series";
import leaderboardRouter from "./leaderboard";
import activityRouter from "./activity";
import userprofileRouter from "./userprofile";
import photoofdayRouter from "./photoofday";
import recommendationsRouter from "./recommendations";
import analyticsRouter from "./analytics";
import subscriptionRouter from "./subscription";
import payoutsRouter from "./payouts";
import supportChatRouter from "./support-chat";
import locksRouter from "./locks";
import verificationRequestsRouter from "./verification-requests";
import adminSubscriptionsRouter from "./admin-subscriptions";
import adminSystemMetricsRouter from "./admin-system-metrics";
import adminIntegrationsRouter from "./admin-integrations";
import adminSeedRouter from "./admin-seed";
import settingsRouter from "./settings";
import photographersRouter from "./photographers";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(photosRouter);
router.use(recommendationsRouter);
router.use(collectionsRouter);
router.use(tagsRouter);
router.use(statsRouter);
router.use(commentsRouter);
router.use(notificationsRouter);
router.use(messagesRouter);
router.use(followsRouter);
router.use(uploadRouter);
router.use(reactionsRouter);
router.use(reportsRouter);
router.use(seriesRouter);
router.use(leaderboardRouter);
router.use(activityRouter);
router.use(userprofileRouter);
router.use(photoofdayRouter);
router.use(analyticsRouter);
router.use(subscriptionRouter);
router.use(payoutsRouter);
router.use(supportChatRouter);
router.use(locksRouter);
router.use(verificationRequestsRouter);
router.use(adminSubscriptionsRouter);
router.use(adminSystemMetricsRouter);
router.use(adminIntegrationsRouter);
router.use(adminSeedRouter);
router.use(settingsRouter);
router.use(photographersRouter);

export default router;
